// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: hello.proto

package helloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Greeter service

type GreeterService interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloReply, error)
	SayHello2(ctx context.Context, opts ...client.CallOption) (Greeter_SayHello2Service, error)
}

type greeterService struct {
	c    client.Client
	name string
}

func NewGreeterService(name string, c client.Client) GreeterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "helloworld"
	}
	return &greeterService{
		c:    c,
		name: name,
	}
}

func (c *greeterService) SayHello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloReply, error) {
	req := c.c.NewRequest(c.name, "Greeter.SayHello", in)
	out := new(HelloReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterService) SayHello2(ctx context.Context, opts ...client.CallOption) (Greeter_SayHello2Service, error) {
	req := c.c.NewRequest(c.name, "Greeter.SayHello2", &HelloRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &greeterServiceSayHello2{stream}, nil
}

type Greeter_SayHello2Service interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*HelloRequest) error
}

type greeterServiceSayHello2 struct {
	stream client.Stream
}

func (x *greeterServiceSayHello2) Close() error {
	return x.stream.Close()
}

func (x *greeterServiceSayHello2) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *greeterServiceSayHello2) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *greeterServiceSayHello2) Send(m *HelloRequest) error {
	return x.stream.Send(m)
}

// Server API for Greeter service

type GreeterHandler interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest, *HelloReply) error
	SayHello2(context.Context, Greeter_SayHello2Stream) error
}

func RegisterGreeterHandler(s server.Server, hdlr GreeterHandler, opts ...server.HandlerOption) error {

	h := &Greeter{hdlr}
	return s.Handle(s.NewHandler(h, opts...))
}

type Greeter struct {
	GreeterHandler
}

func (h *Greeter) SayHello(ctx context.Context, in *HelloRequest, out *HelloReply) error {
	return h.GreeterHandler.SayHello(ctx, in, out)
}

func (h *Greeter) SayHello2(ctx context.Context, stream server.Stream) error {
	return h.GreeterHandler.SayHello2(ctx, &greeterSayHello2Stream{stream})
}

type Greeter_SayHello2Stream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*HelloRequest, error)
}

type greeterSayHello2Stream struct {
	stream server.Stream
}

func (x *greeterSayHello2Stream) Close() error {
	return x.stream.Close()
}

func (x *greeterSayHello2Stream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *greeterSayHello2Stream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *greeterSayHello2Stream) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
