# at https://docs.docker.com/compose/compose-file/
version: '3'

networks:
  pushtx_test:
    external:
      name: pushtx_test

services:
  btc_pool_stats_cron:
    container_name: btc_pool_stats_cron
    image: registry.cn-hongkong.aliyuncs.com/btc-com/pool-web:stats
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./outputs:/app/outputs
      - ./configs/config.yaml:/app/configs/config.yaml
    networks:
      - pushtx_test
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./test_stat_data/db/mysql:/var/lib/mysql
    networks:
      - pushtx_test
